image: node:16

pages:
  image: node:16
  before_script:
    - apt-get update
    - apt-get install -y brotli
  script:
    - mkdir public/
    - cp index.html public/.
    - cp -r css/ public/.
    # Pre-compress assets with gzip
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    # Pre-compress assets with brotli
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec brotli -f -k {} \;
  artifacts:
    paths:
      - public
